# cargo-make tasks
# not very helpful and seems to be executing the tasks 3 times??
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.run-game]
command = "cargo"
args = ["run", "-p", "game_frontend"]

[tasks.test]
command = "cargo"
args = ["test", "-p", "minimax"]

[tasks.bench]
command = "cargo"
args = ["bench", "-p", "minimax"]