[package]
name = "tree_visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minimax = { path = "../minimax" }
graphviz-rust = "0.4.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.1"