name: Test

# adapted from https://github.com/bevyengine/bevy_github_ci_template/blob/main/.github/workflows/ci.yaml

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/**'
    
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  # runs cargo test
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
  
  # runs cargo benchmark
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Install valgrind
      run: sudo apt install valgrind

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.toml') }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '2'

    - run: git checkout $GITHUB_REF^1
    - name: Run iai benchmark on previous commit
      run: cargo bench --bench minimax_bench_iai --quiet >> $GITHUB_STEP_SUMMARY

    - run: git checkout $GITHUB_REF
    - name: Run iai benchmark on latest commit
      run: cargo bench --bench minimax_bench_iai --quiet >> $GITHUB_STEP_SUMMARY
